# Generated by Django 6.0.1 on 2026-01-20 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Security, Cloud Computing, Networking)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what certifications belong in this category')),
                ('icon_class', models.CharField(blank=True, help_text="CSS icon class for display (e.g., 'fa-shield', 'fa-cloud')", max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for UI theming (e.g., #3B82F6 for blue)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Category',
                'verbose_name_plural': 'Certificate Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='certificate_name_37004a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CertificateProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the certification provider (e.g., CompTIA, Microsoft, AWS)', max_length=100, unique=True)),
                ('website', models.URLField(blank=True, help_text='Official website of the provider', null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this provider offers')),
                ('logo', models.ImageField(blank=True, help_text='Provider logo for UI display', null=True, upload_to='providers/%Y/%m/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this provider still active? (Soft delete)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Provider',
                'verbose_name_plural': 'Certificate Providers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='certificate_name_7fcfb0_idx'), models.Index(fields=['is_active'], name='certificate_is_acti_7fb840_idx')],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full name of the certification (e.g., 'CompTIA Security+ CE')", max_length=200)),
                ('certification_id', models.CharField(blank=True, help_text='Unique credential/certification ID from provider (if applicable)', max_length=100)),
                ('issue_date', models.DateField(help_text='Date the certificate was issued')),
                ('expiry_date', models.DateField(blank=True, help_text='Date the certificate expires (leave blank if lifetime certification)', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', help_text='Current status of the certificate', max_length=10)),
                ('certificate_file', models.FileField(blank=True, help_text='Upload certificate file (PDF, image, etc.)', null=True, upload_to='certificates/%Y/%m/')),
                ('verification_url', models.URLField(blank=True, help_text='URL for online certificate verification (if available)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this certificate (renewal requirements, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('user', models.ForeignKey(help_text='Employee who holds this certificate', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Category this certificate belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.certificatecategory')),
                ('provider', models.ForeignKey(help_text='Organization that issued this certificate', on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.certificateprovider')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='certificate_user_id_42f10a_idx'), models.Index(fields=['provider'], name='certificate_provide_8e16c5_idx'), models.Index(fields=['category'], name='certificate_categor_6654e9_idx'), models.Index(fields=['status'], name='certificate_status_31e804_idx'), models.Index(fields=['expiry_date'], name='certificate_expiry__2f5bd0_idx'), models.Index(fields=['-issue_date'], name='certificate_issue_d_b2f3d3_idx')],
            },
        ),
    ]
