# Generated by Django 6.0.1 on 2026-01-20 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this certificate belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.certificatecategory'),
        ),
    ]
