# Generated by Django 6.0.1 on 2026-01-19 21:28

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Company email address - used for login', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('password', models.CharField(help_text='Hashed password - never stored in plain text', max_length=128)),
                ('first_name', models.CharField(help_text='Employee first name', max_length=50)),
                ('last_name', models.CharField(help_text='Employee last name', max_length=50)),
                ('department', models.CharField(blank=True, help_text='Department or team (e.g., Engineering, HR, Sales)', max_length=100)),
                ('position', models.CharField(blank=True, help_text='Job title or role (e.g., Software Engineer, Manager)', max_length=100)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', help_text='User role - determines permissions in the system', max_length=20)),
                ('is_staff', models.BooleanField(default=False, help_text='Can access Django admin panel')),
                ('is_active', models.BooleanField(default=True, help_text='Account status - inactive users cannot log in')),
                ('is_superuser', models.BooleanField(default=False, help_text='Has all permissions without explicitly assigning them')),
                ('profile_image', models.ImageField(blank=True, help_text='Optional profile photo', null=True, upload_to='profiles/%Y/%m/')),
                ('must_change_password', models.BooleanField(default=False, help_text='Force password change on next login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Account creation date')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last successful login timestamp', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last profile update timestamp')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'), models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx')],
            },
        ),
    ]
